apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.storage.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.storage.size }}