spring:
  data:
    mongodb:
      host: localhost #for now I kept localhost
      port: 27017
      database:
      authentication-database: admin
      username:
      password:

management.endpoints.web.exposure.include: '*'

summary:
  host: localhost
  port: 8081